language: php
php:
    - 5.5
    - 5.4
    - hhvm

before_script:
    - wget https://scrutinizer-ci.com/ocular.phar

script:
    - composer install
    - phpunit --bootstrap test/bootstrap.php --coverage-clover coverage.clover test

after_script:
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover